### ISSUE TITLE
Broken API call on line 53 of setup-sheet.py

### ISSUE THREAD

**Issue by incherre** [incherre/book-selector#1]

**Comment by incherre** [comment]
It seems like the issue is that immediately after creating a spreadsheet, sheet1 doesn't exist. It is automatically created some time after.

**Comment by incherre** [comment]
Nope, it's actually that the instance of a spreadsheet object created when the script creates a new spreadsheet doesn't have access to "sheet1" if it is used to make new worksheets.

**Comment by clara-github** [comment]
Looks like while the script no longer breaks, it's still not deleting Sheet1.

**Comment by incherre** [comment]
Works fine for me. Are you using the same book club name as when it broke before? Could be an issue with duplicate sheets.

**Comment by incherre** [comment]
Running delete-all.py added in commit 2bc18920d6b945740e0cd0372e31b9632b33cf72 should give you a blank slate.

**Comment by incherre** [comment]
Bug in the prototype, which has been depreciated.
